import { MappingDictionary } from './types';

// Mapping based on the user's provided image/table
export const POS_MAPPING: MappingDictionary = {
  "BIAYA PONDOKAN/SPP": { kode: "A12", uraian: "Penerimaan, Yusuf Sebastian, SPP" },
  "WAKAF BANGUNAN": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Wakaf Bangunan" },
  "PENDAFTARAN": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Pendaftaran PSB" },
  "BIAYA KESEHATAN": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Kesehatan" },
  "DANA PENGEMBANGAN PESANTREN": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Dana Pengembangan Pesantren" },
  "BIAYA DAFTAR ULANG": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Daftar Ulang" },
  "BIAYA ADMINISTRASI": { kode: "A28", uraian: "Penerimaan, Yusuf Sebastian, Pendapatan Biaya Administrasi" },
  "SUMBANGAN YATIM": { kode: "A17", uraian: "Penerimaan, Yusuf Sebastian, Kafalah" },
  "SUMBANGAN DANA TPG": { kode: "A26", uraian: "Penerimaan, Yusuf Sebastian, Sumbangan Dana TPG" },
  "INFAK PROGRAM TPA": { kode: "A12", uraian: "Penerimaan, Yusuf Sebastian, Infaq Program TPA" },
  "KAFALAH YATIM": { kode: "A17", uraian: "Penerimaan, Yusuf Sebastian, Kafalah" },
  "HUTANG / PIUTANG": { kode: "B23", uraian: "Penerimaan, Yusuf Sebastian, Piutang Guru dan Karyawan" },
  "PENDAPATAN BIAYA ADMIN": { kode: "A28", uraian: "Penerimaan, Yusuf Sebastian, Pendapatan Biaya Administrasi" },
  "LAIN-LAIN": { kode: "A28", uraian: "Penerimaan lain-lain (uang saku, donasi, transfer)" },
  "PARKIR MOBIL": { kode: "A15", uraian: "Penerimaan, Yusuf Sebastian, Parkir inap" },
  "HASIL USAHA PIT": { kode: "A15", uraian: "Hasil usaha (cek)" },
  "WAKAF PERLENGKAPAN ASRAMA": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Wakaf Perlengkapan Asrama" },
  "WAKAF PERLENGKAPAN SEKOLAH": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Wakaf Perlengkapan Sekolah" },
  "BIAYA BUKU / UJIAN PESANTREN": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Buku / Ujian Pesantren" },
  "BIAYA BAHAN SERAGAM": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Bahan Seragam" },
  "DANA BOS MI": { kode: "A14", uraian: "Penerimaan, Yusuf Sebastian, BOS MI" },
  "DANA BOS MTS": { kode: "A14", uraian: "Penerimaan, Yusuf Sebastian, BOS MTs" },
  "DANA BOS MA": { kode: "A14", uraian: "Penerimaan, Yusuf Sebastian, BOS MA" },
  "PUSTAKA IBNU TAIMIYAH": { kode: "A28", uraian: "Penerimaan lain-lain (uang saku, donasi, transfer)" },
  "EKSTRAKURIKULER": { kode: "A26", uraian: "Penerimaan, Yusuf Sebastian, Biaya Ekskul" },
  "LAUNDRY PAKAIAN": { kode: "A15", uraian: "Penerimaan, Yusuf Sebastian, Laundry" },
  "BIAYA KEGIATAN RA": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Kegiatan RA" },
  "BIAYA KEGIATAN MTS/MA": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Kegiatan MTs/MA" },
  "BIAYA PERPUSTAKAAN": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Perpustakaan" },
  "BIAYA SERAGAM": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Bahan Seragam" },
  "BIAYA BAHAN SERAGAM BATIK": { kode: "A23", uraian: "Penerimaan, Yusuf Sebastian, Biaya Bahan Seragam Batik" },
  "TABUNGAN SISWA": { kode: "A26", uraian: "Penerimaan, Yusuf Sebastian, Tabungan Siswa" },
};